# Site settings
title:       k3rn31
email:       7h3.k3rn31@gmail.com
author:      Davide Petilli
description: ""
baseurl:     ""
url:         "http://k3rn31.davidepetilli.com"

# Timezone
timezone: Europe/Rome

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: k3rn31

# Social icons
show_social_icons: true
github_username: k3rn31
stackoverflow_id:
twitter_username: k3rn31
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
